# coding: utf-8

"""
    fastapi-playground

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client._generated.openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_urls_url_list_get(self) -> None:
        """Test case for get_all_urls_url_list_get

        Get All Urls
        """
        pass


if __name__ == '__main__':
    unittest.main()
