# coding: utf-8

"""
    fastapi-playground

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client._generated.openapi_client.api.upload_api import UploadApi


class TestUploadApi(unittest.TestCase):
    """UploadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UploadApi()

    def tearDown(self) -> None:
        pass

    def test_upload_file_upload_post(self) -> None:
        """Test case for upload_file_upload_post

        Upload File
        """
        pass

    def test_upload_files_upload_many_post(self) -> None:
        """Test case for upload_files_upload_many_post

        Upload Files
        """
        pass


if __name__ == '__main__':
    unittest.main()
