#!/bin/sh
# This file is autogenerated - DO NOT EDIT!

set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${BASE_DIR}/.."
(
cd ${REPO_DIR}
kubectl create namespace fastapi-playground --dry-run=client -o yaml | kubectl apply -f -
helm upgrade --install my-minio oci://registry-1.docker.io/bitnamicharts/minio -n fastapi-playground -f minio/values.yaml
)
